
# Discussion
The aim of this study was to explore the effectiveness of psychological therapy delivered within a tertiary care therapy service using a benchmarking approach to contextualise intake distress and outcomes produced. The baseline severity of initial distress was higher in the current study than any of the available OQ-45 benchmarks. The pooled pre-post therapy effect-size for the current study was small and also smaller than the two employed benchmarks from tertiary care services and OQ-45 outcome studies. The three treatment modalities showed equivalent rates of effectiveness evidenced through CI overlap with SPS pooled effect-size. SPS individual patient response rates for reliable improvement and recovery were comparable to a US OQ-45 community mental health center benchmark [@Hansen2002a].
Growth curve trajectories demonstrated that OQ-45 scores reduced by 0.5 points per session, but that this rate declined in line with significant curvi-linear trends (quadratic and cubic). There was no significant difference in change over time between treatment modalities.

## Contribution to the Evidence Base
Because tertiary care services differ markedly from primary/secondary care services (i.e. longer treatment, specialist interventions, marked distress and delivering therapy to those that have not responded to prior treatments), it is necessary that the effectiveness of such services is assessed. Prior UK tertiary care outcome studies have been particularly small [n = <50, @Douglas2016a; @Paley2008a] making it hard to generalize results to larger populations, comment on service design or make practice recommendations.

The current study found greater initial distress status than a range of benchmarks from other service sectors which have employed the OQ-45. This finding provides support to the notion that tertiary care patients tend to present with greater levels of psychological distress and are therefore possibly a different clinical population. This was to the extent that patients in the current study showed, on average, higher levels of distress than US acute/short stay hospital inpatients [@Doerfler2002]. As the current study was the first (to our knowledge) UK study to employ the OQ-45, it is not clear as to whether the elevated scores in the current study are solely due to differences in service/sector. It is possible that differences are in part due to a broader difference between UK and US samples and societies. For example is has been demonstrated that out-patient and community norms are higher in the UK than the US for a number of measures of psychological distress [@Francis1990; @Ryan2007a]. Further use of the OQ-45 in other UK services/sectors is necessary in order to provide a more valid comparison of baseline distress between UK service sector patients. As the available US initial distress benchmarks were more than 15 years old, it is also possible that these may not reflect contemporary levels of initial distress.

This study demonstrated the effectiveness of tertiary care therapy using a much greater sample size than has previously been reported in the UK. Effectiveness within this study was based on the first care period for each patient. For an unknown proportion of patients this will have included treatments delivered consecutively, and with periods of waiting between treatments. Effectiveness should therefore be considered to represent tertiary care episodes, and not necessarily single treatments.

The finding that non-linear trends best fit each of the outcome variables was consistent with the dose-response evidence base [@Bone2021; @Howard1986; @Robinson2020]. The time trends of best fit for the OQ-45 total, symptom distress and interpersonal relationships (all cubic) suggest that patients who remain in therapy for very long periods are at risk of starting to deteriorate. More specifically, patients with very long treatments (i.e. over 100) had a smaller pooled effect-size, but without raised rates of deterioration. This suggests that patients engaged in long treatments tend to either (i) make smaller over-all improvements, and with that improvements occurring in earlier stages of treatment; or, (ii) can be classed as ‘non-responders.’ For social role (log-linear), improvements were rapid in the early stage of treatment, while further improvements were made with a negatively decelerating rate. These findings are consistent with the body of literature demonstrating that the majority of improvements made within therapy are achieved within the early stages [@Bone2021; @Robinson2020]. Practically, this means that patients may show limited added benefit from long forms of psychotherapy.

The relatively high rate of patients who (based on the OQ-45) did not respond to treatment (deterioration and no change combined = 59.89%) may be due to a range of factors which are considered to be more prevalent within complex client groups [e.g. compulsion to repeat, @vanderKolk1989]. These factors may have been also due to reasons beyond the therapy room that were not measured in the current study such as the influence of social disadvantage, life circumstances or chronicity of prior traumas [@Finegan2018]. These potential reasons for non-response should be empirically explored within future tertiary care therapy studies exploring predictors of treatment response/non-response.

It is not clear as to why social role was the only sub-scale that continued to make improvements (albeit at a reducing rate), or why interpersonal and symptom distress did not. This pattern is different to patterns identified in prior empirical studies [@Schilling2020; @White2015]; these have included (i) alliance and motivational difficulties; (ii) social support and life event difficulties; and (iii) indistinguishable patterns. This pattern may be more characteristic of patients who access UK tertiary care therapy. The finding that interpersonal problems was a predictor of not responding to treatment was consistent with prior evidence [@Probst2020]. Two of the therapies delivered (i.e. PAT and CAT) focus on interpersonal issues, but this does not seem to have made a great difference.

The overall effect-size observed in the current study was smaller than that reported by @Paley2008a. The overall effect-size was also less than that shown in the @Johansson2014 Canadian tertiary care service. As these studies used different outcome measures, it was not possible to say whether the two studies were comparable on baseline distress. These measures may also differ in sensitivity to change. There is a need for more tertiary care outcome studies which are comparable in size and design to the current study in order to provide a more valid set of benchmarks.
The overall effect-size for this study was likely to have been suppressed by patients with long treatments who do not respond (hence the cubic finding).

Based on the growth-curve plots, there was evidence that growth became negative from the point of approximately 150 sessions for OQ-45 total score. This is consistent with the literature which shows a lack of added value for very long treatment durations [@Bone2021; @Robinson2020]. Negative growth was influenced by two sub-scales with cubic trends (symptom distress and interpersonal). In other words, patients in the latter stages of long treatments show particularly elevated rates of interpersonal distress and symptom distress. While tertiary care psychological therapy will, in many cases, intend to work on inter-personal difficulties and symptoms distress, those who stay in treatment for very long periods (over 100 sessions) make limited additional improvements, despite the theoretical grounding of the models often being used.

There was a significant difference between SPS recovery rates and the OQ-45 recovery benchmarks. More specifically, less patients in the current sample made full recovery but more made a reliable improvement. It is a likely that this difference is a reflection of the higher initial baseline distress in the SPS sample (i.e., a greater amount of change is required to fall under the clinical threshold to meet full recovery). When compared to the community mental health center sub-group of the OQ-45 recovery benchmarks, which was suspected to be most comparable to SPS, there was no significant difference in recovery rates. Taken together with the above effect-sizes (Cohen’s *d*), the current study found that tertiary care patients showed smaller average (within-group) change, but comparable rates of individual change to other service sectors. These comparisons do not consider an array of potential differences in treatments (e.g., number of sessions, clinician experience, heterogeneity in the clinical presentations and complexity of the patient samples).

The current study found limited evidence for significant differential rates of effectiveness between different psychological modalities. CAT showed the highest indices of average (within-group) change (Cohen’s *d*), however the accompanying confidence intervals overlapped with the effect-sizes of both of the other treatment modalities. The potential of CAT in tertiary care may be the relatively brief treatment contract and the relational focus. A recent meta-analysis of CAT [@Hallam2021] showed its differential efficacy in typically complex client groups.  In this study, both CAT and CBT showed superior levels of ‘service efficiency’ based on providing comparable clinical effectiveness, but within the boundaries of significantly shorter treatment contacts. It is possible that PAT treatments were skewed by a small number of patients with very long care periods. The comparable rates of effectiveness (Cohen’s *d* and response rates) between the three modalities provides further support to the equivalence paradox; that is, bone fide psychotherapies delivered in routine care tend not to significantly differ in terms of effectiveness.

## Limitations
There were nine additional main study limitations: (i) by focusing on pre-post change it is not possible to say to what extent the observed results are due to the allocated treatment or due to other potential confounds (e.g. regression to the mean, spontaneous remission, co-occurring pharmacotherapy); (ii) as outcome measurement was not conducted at every session, the level of detail regarding change over time is limited in granularity; (iii) the pre-post effect-size calculation did not include patients who were accepted for treatment but who did not attend the first appointment (i.e. treatment rejectors), this study may therefore have over-inflated effect-sizes; (iv) concurrent treatments (e.g. pharmacological treatment, other involved services) were not known, and which may account for a range of within-group differences in effectiveness; (v) the absence of treatment fidelity measures means that the study is unable to assess the degree to which treatments were delivered as intended; (vi) frequency of clinical supervision was not reported; (vii) the lack of UK normative data for the OQ-45 means that recovery rates may be inaccurate,
(viii) findings were exclusively based upon a single self-report measurement tool, it was therefore not possible to comment upon effectiveness that may be derived through other methods (e.g. clinician rated, change in health-care utilisation, change in harm events). While there are analysis methods available to calculate change indices and cut-off scores using only the current available sample [e.g. @Morley2014] these methods are less precise.
Finally, the current study was purely quantitative and therefore little is known about the patient experience of the changes recorded.

## Implications: Research, Policy & Practice
The finding that initial distress was higher than benchmarks for other sectors fits with the intention that tertiary care services cater for patients with particularly high levels of distress.
The current study found that tertiary care therapy services produce significant change over time with small rates of therapeutic effectiveness. Effect-sizes are likely to be suppressed by a sub-group of patients who appear to not respond to psychological treatment, despite considerable numbers of sessions. On average, growth appears to become negative from approximately 150 sessions. The identification of a group of patients that are ‘treatment non-responders’ in a larger sample of patients referred to a tertiary service for people that have been previously ‘treatment resistant’, means that tertiary services need to identify ‘non-responders’ at the earliest possibility. Whilst services want to help (or possibly ‘rescue’), there may be some patients for whom psychological pain is enduring and help is ineffective and this means alternative management strategies need to be developed and tested for this population. Despite this, it should be noted that other indices of effectiveness (e.g. rates of harm, post-treatment rates of health service utilisation) were not considered and which may provide alternative justifications for treatment continuation. Utilising available information regarding not-on-track status during clinical supervision and patient feedback may allow for consideration of earlier, necessary treatment termination, and which may subsequently improve the efficiency of treatments [@deJong2021].

## Future Research

Further practice-based evidence is clearly required in the area of tertiary care psychotherapy. Such studies are particularly needed to provide more representative UK benchmarking comparisons. Studies should strive to employ a session-by-session outcome measurement approach that can reduce data missingness and clinician bias. Future studies comparing differential rates of modality effectiveness should aim to provide more adequate sample numbers across treatment comparison groups. Mixed methods would also be useful. Future studies should also employ fidelity measures to ensure treatments compared are treatments intended. Future studies should pay attention to other indices of treatment success (e.g. health care utilisation, harm events). Attention should be paid to differential rates of effectiveness between therapists (i.e. the role of ‘therapist effects’) however this would need a much larger sample. Finally, psychometric validation studies for the OQ-45 have taken place in various countries outside the US [e.g., @Jong2007; @Wennberg2010], but not yet in the UK; this is an important next step. 

## Conclusions

The current study explored the effectiveness of psychological therapy within a tertiary care therapy service. Patient initial distress was higher than a range of service benchmarks, indexing a highly distressed clinical population. Despite delivery of relatively lengthy interventions, the size of pre-post effectiveness outcome was small. The study effect-size was lower than a meta-analytic benchmark of studies employing the OQ-45 and a separate benchmark for a Canadian tertiary care service. Effectiveness was seemingly reduced by a number of patients receiving very long treatments and who do not improve during these interventions. Cohen’s *d* and response rates were generally equivalent across different treatment modalities. Change in tertiary patients occurred over time and with a cubic form. Further evaluations of effectiveness of tertiary care psychological therapy services is required and particularly the development of service delivery models that can be responsive to lack of change in patients whilst retaining fidelity to the theory and methods of the interventions delivered. 






